FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir fastapi uvicorn pydantic joblib numpy

COPY src/ ./src/

CMD ["uvicorn", "src.api.run_api:app", "--host", "0.0.0.0", "--port", "8000"]